# Generated by Django 4.2.5 on 2023-10-02 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('company_name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.companyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.buyerinfo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.companyinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.vendorinfo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.producttype'),
        ),
        migrations.AddField(
            model_name='buyerinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.companyinfo'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.companyinfo'),
        ),
    ]
