# Generated by Django 4.2.4 on 2023-08-22 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='fullname',
        ),
    ]
