# Generated by Django 4.2.4 on 2023-08-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_todo_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='fullname',
            new_name='name',
        ),
    ]
